spring:
  application:
    name: shop-service
mybatis:
   mapperLocations: classpath:mapper/*.xml
   config-location: classpath:config/mybatis-config.xml
server:
  port: 8674
  discovery-port: 8671
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8671/eureka/


